version: '3'
services:
  synche:
    container_name: synche-server
    restart: always
    build: .
    volumes:
      - /home/tara/synche/synche-server.yaml:/root/synche/synche-server.yaml
    ports:
      - 0.0.0.0:9449:9449
      - 0.0.0.0:2121:2121
    networks:
      - backend
    depends_on:
      - "db"
  db:
    container_name: synche-db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: synche
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 3306:3306
    #volumes:
    # - /var/lib/mariadb:/var/lib/mysql
    networks:
      - backend

networks:
  backend:
    driver: bridge