name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Install swagger
      run: |
         curl -o /usr/local/bin/swagger -L'#' "https://github.com/go-swagger/go-swagger/releases/download/v0.27.0/swagger_linux_amd64"
         chmod +x /usr/local/bin/swagger
         go get github.com/vektra/mockery/v2/.../
         swagger version

    - name: Go Generate
      run: |
        make generate
        go generate ./...

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
